<br />

        <table width="100%" cellspacing="0">
			<tr><td class="list-column-blue" colspan="2">Affiliates \/\/\/\/\/\/\/\/</td>
				<td class="list-column-gray">Leads</td>
				<td class="list-column-green" colspan="13">Sales \/\/\/\/\/\/\/\/</td>
				<td class="list-column-red" colspan="2">Refunds \/\/\/\/\/\/\/\/</td>
				<td class="list-column-yellow" colspan="2">Declines \/\/\/\/\/\/\/\/</td>
			</tr>
          	<tr><td class="list-column-blue" width="5%">ID</td>
            	<td class="list-column-blue" width="15%">Affiliate Name</td>
            	<td class="list-column-gray" width="5%">Count</td>
            	<td class="list-column-green" width="5%">Orig#</td>
            	<td class="list-column-green" width="5%">Orig$</td>
            	<td class="list-column-green" width="5%">New#</td>
            	<td class="list-column-green" width="5%">New$</td>
            	<td class="list-column-green" width="1%">+</td>
            	<td class="list-column-green" width="5%">Rebill#</td>
            	<td class="list-column-green" width="5%">Rebill$</td>
            	<td class="list-column-green" width="1%">+</td>
            	<td class="list-column-green" width="5%">Saved#</td>
            	<td class="list-column-green" width="5%">Saved$</td>
            	<td class="list-column-green" width="1%">=</td>
            	<td class="list-column-green" width="5%">Total#</td>
            	<td class="list-column-green" width="5%">Total$</td>
            	<td class="list-column-red" width="5%">Refund#</td>
            	<td class="list-column-red" width="5%">Refund$</td>
            	<td class="list-column-yellow" width="5%">Declined#</td>
            	<td class="list-column-yellow" width="5%">Declined$</td>
            </tr>
<?php
$i = 0;
if ($this->list_error)
echo "<tr><td align=\"center\" colspan=\"20\">$this->list_error</td>";

else
foreach($this->records as $r)
echo "
<tr style='cursor:pointer;' onmouseover=\"this.style.backgroundColor='#222';\" onmouseout=\"this.style.backgroundColor='';\">
<td class=\"list-row-blue\" onclick=\"AffiliateReport('".$r['user_id']."');\">$r[user_id]</td>
<td class=\"list-row-blue\" onclick=\"AffiliateReport('".$r['user_id']."');\">".(strlen($r['business']) > 0 ? $r['business'] : "$r[user_last], $r[user_first]")."</td>
<td class=\"list-row-gray\" onclick=\"AffiliateReport('".$r['user_id']."');\">$r[lead_count]</td>
<td class=\"list-row-green\" onclick=\"AffiliateReport('".$r['user_id']."');\">$r[original_sale_count]</td>
<td class=\"list-row-green\" onclick=\"AffiliateReport('".$r['user_id']."');\">$r[original_sale_sales]</td>
<td class=\"list-row-green\" onclick=\"AffiliateReport('".$r['user_id']."');\">$r[new_sale_count]</td>
<td class=\"list-row-green\" onclick=\"AffiliateReport('".$r['user_id']."');\">$r[new_sale_sales]</td>
<td class=\"list-row-green\" onclick=\"AffiliateReport('".$r['user_id']."');\"></td>
<td class=\"list-row-green\" onclick=\"AffiliateReport('".$r['user_id']."');\">$r[rebill_count]</td>
<td class=\"list-row-green\" onclick=\"AffiliateReport('".$r['user_id']."');\">$r[rebill_sales]</td>
<td class=\"list-row-green\" onclick=\"AffiliateReport('".$r['user_id']."');\"></td>
<td class=\"list-row-green\" onclick=\"AffiliateReport('".$r['user_id']."');\">$r[saved_count]</td>
<td class=\"list-row-green\" onclick=\"AffiliateReport('".$r['user_id']."');\">$r[saved_sales]</td>
<td class=\"list-row-green\" onclick=\"AffiliateReport('".$r['user_id']."');\"></td>
<td class=\"list-row-green\" onclick=\"AffiliateReport('".$r['user_id']."');\">".($r['new_sale_count']+$r['rebill_count']+$r['saved_count'])."</td>
<td class=\"list-row-green\" onclick=\"AffiliateReport('".$r['user_id']."');\">".($r['new_sale_sales']+$r['rebill_sales']+$r['saved_sales'])."</td>
<td class=\"list-row-red\" onclick=\"AffiliateReport('".$r['user_id']."');\">$r[refund_count]</td>
<td class=\"list-row-red\" onclick=\"AffiliateReport('".$r['user_id']."');\">$r[refund_sales]</td>
<td class=\"list-row-yellow\" onclick=\"AffiliateReport('".$r['user_id']."');\">$r[declined_count]</td>
<td class=\"list-row-yellow\" onclick=\"AffiliateReport('".$r['user_id']."');\">$r[declined_sales]</td>
</tr>
</tr><tr><td style=\"background:#ddd;margin:0;padding:0;border:0;\" id=\"user_$r[user_id]\" colspan=\"18\"></td></tr>
";
?>            
            </tr></table>

<?//= ($this->paging ? $this->paging : "") ?>

            </form>            
            
    </div>  
</div>