<div id="center">
	<div id="mids">	
  		<h1><span style="float:right;margin-right:10px;"><form action="#"><input type="submit" class="submit" value="Add A Campaign" onclick="showForm('save-pane')" /></form></span> &nbsp;Campaigns <?php if ($this->save_success) { ?><span id="alert"><?php echo $this->save_success ?></span><?php } ?></h1>
    	<img src="/img/break.jpg" /><br /><br />
        <table width="100%" cellspacing="0">
          	<tr><td class="list-column" width="1">ID</td>
            	<td class="list-column">Campaign Name</td>
            	<td class="list-column">Offer</td>
            	<td class="list-column">Pages</td>
            	<td class="list-column">Countries</td>
            	<td class="list-column" colspan="2">Forms</td>
            	<td class="list-column">Create Date</td>
            	<td class="list-column" colspan="2">&nbsp;</td>                    
            </tr>
<?php
$i = 0;
if ($this->list_error)
echo "<tr><td align=\"center\" colspan=\"15\">$this->list_error</td>";

else
foreach($this->records as $r)
echo "
<tr style='cursor:pointer;".($this->save_id == $r['camp_id'] ? "background:#090;'" : "' onmouseover=\"this.style.backgroundColor='#222';\" onmouseout=\"this.style.backgroundColor='';\"").">
<td class=\"list-row\">$r[camp_id]</td>
<td class=\"list-row\">$r[campaign]</td>
<td class=\"list-row\">$r[offer_name] ($r[offer_cost])</td>
<td class=\"list-row\">$r[pages] page(s)</td>
<td class=\"list-row\">$r[countries]</td>
<td class=\"list-row\"><a href=\"/console/campaign/form/multi/id/$r[camp_id]\">multi</a></td>
<td class=\"list-row\"><a href=\"/console/campaign/form/single/id/$r[camp_id]\">single</a></td>
<td class=\"list-row\">$r[created]</td>
<td class=\"list-row\" width=\"1\">".($r['disable'] > 0 ? "<a class=\"enable\" href=\"/console/campaign/enable/$r[camp_id]\">enable</a>" : "<a class=\"disable\" href=\"/console/campaign/disable/$r[camp_id]\">disable</a>")."</td>
<td class=\"list-row\" width=\"1\"><a class=\"edit\" href=\"/console/campaign/edit/$r[camp_id]\">edit</a></td>
</tr>
";
?>            
            </tr></table>
    </div>  
</div>





<div id="save-pane" style="display:<?= ($this->save_error ? "block" : "none") ?>">
<h1>Add A Campaign</h1>

<?php if (is_string($this->save_error)) { ?><ul class="errors"><li><?= $this->save_error ?></li></ul><br /><?php } ?>

<form name="save-pane" method="POST" action="/console/campaign/save/1">

<table id="save-form" class="form" cellspacing="10" width="100%">
	<tr>
		<td class="required" width="30%">Campaign Name: <br /> <font class="note">(max. 64)</font></td>
		<td class="value" width="70%"><?= $this->inputs[1] ?></td>
	</tr>
	<tr>
		<td class="required">Number of Pages:</td>
		<td class="value"><?= $this->inputs[2] ?></td>
		
	</tr>
	<tr>
		<td class="required">Attach an Offer:</td>
		<td class="value"><?= $this->inputs[3] ?></td>
	</tr>
	<tr>
		<td class="laben">Add an Upsell Offer:</td>
		<td class="value"><?= $this->inputs[4] ?></td>
	</tr>
	<tr>
		<td class="laben">Add a Bump Offer:</td>
		<td class="value"><?= $this->inputs[5] ?></td>
	</tr>
	<tr>
		<td class="label" colspan="2">Select Countries Where This Campaign Will Run:</td>
	</tr>
	<tr>
		<td class="value" colspan="2">
		<table width="100%" border="0">
			<tr><td valign="top" width="49%"><?= $this->inputs[6] ?></td><td>&nbsp;</td><td valign="top" width="49%"><?= $this->inputs[7] ?></td></tr>
		</table>
		</td>
	</tr>
	<tr>
		<td class="label" colspan="2">Select Shipping Methods For This Campaign (if shippable):</td>
	</tr>
	<tr>
		<td class="value" colspan="2">
		<table width="100%" border="0">
			<tr><td valign="top" width="49%"><?= $this->inputs[8] ?></td><td>&nbsp;</td><td valign="top" width="49%"><?= $this->inputs[9] ?></td></tr>
		</table>
		</td>
	</tr>
	<tr>
		<td class="laben">Use The Impulse Marketing <br /> Team For This Campaign:</td>
		<td class="value"><?= $this->inputs[10] ?> &nbsp; <?= $this->inputs[11] ?> &nbsp; Impulse Campaign ID</td>
	</tr>
	
</table><!-- /#save-form -->

<div id="save-actions" class="actions">
	<input type="submit" class="submit" value="Save" onclick="selAll(countries);selAll(shippers);" />
	<input type="button" class="submit" value="Cancel" onclick="hideForm('save-pane')" />
</div><!-- /#top-actions -->

</form>

</div><!-- /#save-pane -->

<div id="modal" style="display:<?= ($this->save_error ? "block" : "none") ?>"></div><!-- /#modal -->