<div id="center">
	<div id="mids">	
  		<h1><span style="float:right;margin-right:10px;"><form action="#"><input type="submit" class="submit" value="Add A Product" onclick="showForm('save-pane')" /></form></span> &nbsp;Products <?php if ($this->save_success) { ?><span id="alert"><?php echo $this->save_success ?></span><?php } ?></h1>
    	<img src="/img/break.jpg" /><br /><br />
        <table width="100%" cellspacing="0">
          	<tr><td class="list-column" width="1">ID</td>
            	<td class="list-column">Product Name</td>
            	<td class="list-column">Sku#</td>
            	<td class="list-column">Unit Cost</td>
            	<td class="list-column">Weight</td>
            	<td class="list-column">Login</td>
            	<td class="list-column">Create Date</td>
            	<td class="list-column" colspan="2">&nbsp;</td>                    
            </tr>
<?php
$i = 0;
if ($this->list_error)
echo "<tr><td align=\"center\" colspan=\"10\">$this->list_error</td>";

else
foreach($this->records as $r)
echo "
<tr style='cursor:pointer;".($this->save_id == $r['prod_id'] ? "style='background:#090;'" : "' onmouseover=\"this.style.backgroundColor='#222';\" onmouseout=\"this.style.backgroundColor='';\"").">
<td class=\"list-row\">$r[prod_id]</td>
<td class=\"list-row\">$r[product_name]</td>
<td class=\"list-row\">$r[product_sku]</td>
<td class=\"list-row\">$r[product_cost]</td>
<td class=\"list-row\">".($r['product_size'] > 0 ? $r['product_size'] : "")."</td>
<td class=\"list-row\">".($r['has_login'] > 0 ? "<a href=\"/console/product/form/$r[prod_id]\">form</a>" : "&nbsp;")."</td>
<td class=\"list-row\">$r[created]</td>
<td class=\"list-row\" width=\"1\">".($r['disable'] > 0 ? "<a class=\"enable\" href=\"/console/product/enable/$r[prod_id]\">enable</a>" : "<a class=\"disable\" href=\"/console/product/disable/$r[prod_id]\">disable</a>")."</td>
<td class=\"list-row\" width=\"1\"><a class=\"edit\" href=\"/console/product/edit/$r[prod_id]\">edit</a></td>
</tr>
";
?>            
            </tr></table>
    </div>  
</div>





<div id="save-pane" style="display:<?= ($this->save_error ? "block" : "none") ?>">
<h1>Add A Product</h1>

<?php if (is_string($this->save_error)) { ?><ul class="errors"><li><?= $this->save_error ?></li></ul><br /><?php } ?>

<form name="save-pane" method="POST" action="/console/product/save/1">

<table id="save-form" class="form" cellspacing="10" width="100%">
	<tr>
		<td class="required" width="30%">Product Name: <br /> <font class="note">(max. 64)</font></td>
		<td class="value" width="70%"><?= $this->inputs[1] ?></td>
	</tr>
	<tr>
		<td class="required" valign="top">Product Description: <br /> <font class="note">(max. 255)</font></td>
		<td class="value"><?= $this->inputs[2] ?></td>
	</tr>
	<tr>
		<td class="label">Product Sku#: <br /> <font class="note">(max. 32)</font></td>
		<td class="value"><?= $this->inputs[3] ?></td>
	</tr>
	<tr>
		<td class="label">Unit Cost: <br /> <font class="note">(eg. 49.95 USD)</font></td>
		<td class="value"><?= $this->inputs[4] ?></td>
	</tr>
	<tr>
		<td class="label">Unit Weight: <br /> <font class="note">(in OZ.)</font></td>
		<td class="value"><?= $this->inputs[5] ?></td>
	</tr>
	<tr>
		<td class="label">Has Login?</td>
		<td class="value"><?= $this->inputs[6] ?></td>
	</tr>

</table><!-- /#save-form -->

<div id="save-actions" class="actions">
	<input type="submit" class="submit" value="Save" />
	<input type="button" class="submit" value="Cancel" onclick="hideForm('save-pane')" />
</div><!-- /#top-actions -->

</form>

</div><!-- /#save-pane -->

<div id="modal" style="display:<?= ($this->save_error ? "block" : "none") ?>"></div><!-- /#modal -->