<?php 
// application/layouts/scripts/layout.phtml

echo $this->doctype() ?>

<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>ProleroInc CRM</title>
<?php echo $this->headLink()->appendStylesheet('/css/style.css') ?>

<script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/dojo/1.3.2/dojo/dojo.xd.js" djConfig="parseOnLoad: true, isDebug: false"></script>
<script language="JavaScript" src="/js/calendar_us.js"></script>
<script language="JavaScript" src="/js/script.js"></script>
<script type="text/javascript">
dojo.require('dojo.parser');
dojo.require('dijit.Dialog');
dojo.require("dijit.form.DateTextBox");
</script>
<link rel="stylesheet" href="/css/calendar.css" />
</head>
<body class="tundra" onload="init();">
 <div id="main">
    <ul id="top">
        	<li><img src="/img/logo.jpg" class="logo" /></li>
<li><a href="<?php echo $this->url( array('controller'=>'console'), 'default', true) ?>">DASHBOARD</a></li>
            <li><img src="/img/seperate.jpg" class="logo" /></li>
<li><a href="<?php echo $this->url( array('controller'=>'console','action'=>'order'), 'default', true) ?>">ORDERS</a></li>
            <li><img src="/img/seperate.jpg" class="logo" /></li>
<li><a href="<?php echo $this->url( array('controller'=>'console','action'=>'report'), 'default', true) ?>">REPORTS</a></li>
            <li><img src="/img/seperate.jpg" class="logo" /></li>
<li><a href="<?php echo $this->url( array('controller'=>'console','action'=>'product'), 'default', true) ?>">PRODUCTS</a></li>
            <li><img src="/img/seperate.jpg" class="logo" /></li>
<li><a href="<?php echo $this->url( array('controller'=>'console','action'=>'offer'), 'default', true) ?>">OFFERS</a></li>
            <li><img src="/img/seperate.jpg" class="logo" /></li>
<li><a href="<?php echo $this->url( array('controller'=>'console','action'=>'campaign'), 'default', true) ?>">CAMPAIGNS</a></li>
            <li><img src="/img/seperate.jpg" class="logo" /></li>
<li><a href="<?php echo $this->url( array('controller'=>'console','action'=>'profile'), 'default', true) ?>">PROFILE</a></li>
            <li><img src="/img/seperate.jpg" class="logo" /></li>
<li><a href="<?php echo $this->url( array('controller'=>'console','action'=>'user'), 'default', true) ?>">USERS</a></li>
            <li><img src="/img/seperate.jpg" class="logo" /></li>
<li><a href="<?php echo $this->url( array('controller'=>'console','action'=>'logout'), 'default', true) ?>">LOGOUT</a></li>
    </ul>

 <?php echo $this->layout()->content ?>

 </div>
</body>
</html>